/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApplicationStatus = IDL.Variant({
  'Applied' : IDL.Null,
  'Rejected' : IDL.Null,
  'Interviewing' : IDL.Null,
  'Offer' : IDL.Null,
  'Archived' : IDL.Null,
});
export const ApplicationSource = IDL.Variant({
  'referral' : IDL.Null,
  'network' : IDL.Null,
  'direct' : IDL.Null,
  'job_board' : IDL.Null,
  'recruiter' : IDL.Null,
});
export const JobType = IDL.Variant({
  'onsite' : IDL.Null,
  'remote' : IDL.Null,
  'hybrid' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const AddApplicationArgs = IDL.Record({
  'fitScoreConfidence' : IDL.Opt(IDL.Nat),
  'status' : ApplicationStatus,
  'aiSuggestion' : IDL.Opt(IDL.Text),
  'source' : ApplicationSource,
  'jobType' : JobType,
  'fitScore' : IDL.Opt(IDL.Nat),
  'tags' : IDL.Vec(IDL.Text),
  'jobUrl' : IDL.Text,
  'appliedDate' : Timestamp,
  'notes' : IDL.Text,
  'companyName' : IDL.Text,
  'isHighPotential' : IDL.Bool,
  'salaryMax' : IDL.Opt(IDL.Nat),
  'salaryMin' : IDL.Opt(IDL.Nat),
  'position' : IDL.Text,
  'location' : IDL.Text,
});
export const AppId = IDL.Nat;
export const UserId = IDL.Principal;
export const Application = IDL.Record({
  'id' : AppId,
  'fitScoreConfidence' : IDL.Opt(IDL.Nat),
  'status' : ApplicationStatus,
  'aiSuggestion' : IDL.Opt(IDL.Text),
  'source' : ApplicationSource,
  'jobType' : JobType,
  'userId' : UserId,
  'fitScore' : IDL.Opt(IDL.Nat),
  'tags' : IDL.Vec(IDL.Text),
  'lastUpdated' : Timestamp,
  'jobUrl' : IDL.Text,
  'appliedDate' : Timestamp,
  'notes' : IDL.Text,
  'companyName' : IDL.Text,
  'isHighPotential' : IDL.Bool,
  'salaryMax' : IDL.Opt(IDL.Nat),
  'salaryMin' : IDL.Opt(IDL.Nat),
  'position' : IDL.Text,
  'location' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DateRange = IDL.Record({
  'toDate' : Timestamp,
  'fromDate' : Timestamp,
});
export const ApplicationsOverTime = IDL.Record({
  'date' : Timestamp,
  'count' : IDL.Nat,
});
export const ApplicationsByJobType = IDL.Record({
  'jobType' : JobType,
  'count' : IDL.Nat,
});
export const ApplicationsBySource = IDL.Record({
  'source' : ApplicationSource,
  'count' : IDL.Nat,
});
export const AnalyticsResult = IDL.Record({
  'offerRate' : IDL.Float64,
  'total' : IDL.Nat,
  'overTime' : IDL.Vec(ApplicationsOverTime),
  'interviewRate' : IDL.Float64,
  'avgTimeToOffer' : IDL.Float64,
  'responseRate' : IDL.Float64,
  'byJobType' : IDL.Vec(ApplicationsByJobType),
  'bySource' : IDL.Vec(ApplicationsBySource),
});
export const GetApplicationsArgs = IDL.Record({
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'statusFilter' : IDL.Opt(ApplicationStatus),
});
export const GetApplicationsResult = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'applications' : IDL.Vec(Application),
});
export const AiInsight = IDL.Record({
  'message' : IDL.Text,
  'category' : IDL.Text,
  'priority' : IDL.Nat,
});
export const ParsedJobDetails = IDL.Record({
  'fitScoreConfidence' : IDL.Opt(IDL.Nat),
  'rawJson' : IDL.Text,
  'jobType' : IDL.Opt(JobType),
  'fitScore' : IDL.Opt(IDL.Nat),
  'tags' : IDL.Vec(IDL.Text),
  'notes' : IDL.Text,
  'companyName' : IDL.Text,
  'salaryMax' : IDL.Opt(IDL.Nat),
  'salaryMin' : IDL.Opt(IDL.Nat),
  'position' : IDL.Text,
  'location' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateApplicationArgs = IDL.Record({
  'id' : AppId,
  'fitScoreConfidence' : IDL.Opt(IDL.Nat),
  'status' : ApplicationStatus,
  'aiSuggestion' : IDL.Opt(IDL.Text),
  'source' : ApplicationSource,
  'jobType' : JobType,
  'fitScore' : IDL.Opt(IDL.Nat),
  'tags' : IDL.Vec(IDL.Text),
  'jobUrl' : IDL.Text,
  'appliedDate' : Timestamp,
  'notes' : IDL.Text,
  'companyName' : IDL.Text,
  'isHighPotential' : IDL.Bool,
  'salaryMax' : IDL.Opt(IDL.Nat),
  'salaryMin' : IDL.Opt(IDL.Nat),
  'position' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addApplication' : IDL.Func([AddApplicationArgs], [Application], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteApplication' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAnalytics' : IDL.Func([DateRange], [AnalyticsResult], ['query']),
  'getApplication' : IDL.Func([IDL.Nat], [IDL.Opt(Application)], ['query']),
  'getApplications' : IDL.Func(
      [GetApplicationsArgs],
      [GetApplicationsResult],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGrokApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
  'getInsights' : IDL.Func([], [IDL.Vec(AiInsight)], []),
  'initSampleData' : IDL.Func([], [IDL.Nat], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'parseJobUrl' : IDL.Func([IDL.Text], [ParsedJobDetails], []),
  'searchApplications' : IDL.Func([IDL.Text], [IDL.Vec(Application)], []),
  'setGrokApiKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateApplication' : IDL.Func(
      [UpdateApplicationArgs],
      [IDL.Opt(Application)],
      [],
    ),
  'updateApplicationStatus' : IDL.Func(
      [IDL.Nat, ApplicationStatus],
      [IDL.Opt(Application)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApplicationStatus = IDL.Variant({
    'Applied' : IDL.Null,
    'Rejected' : IDL.Null,
    'Interviewing' : IDL.Null,
    'Offer' : IDL.Null,
    'Archived' : IDL.Null,
  });
  const ApplicationSource = IDL.Variant({
    'referral' : IDL.Null,
    'network' : IDL.Null,
    'direct' : IDL.Null,
    'job_board' : IDL.Null,
    'recruiter' : IDL.Null,
  });
  const JobType = IDL.Variant({
    'onsite' : IDL.Null,
    'remote' : IDL.Null,
    'hybrid' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const AddApplicationArgs = IDL.Record({
    'fitScoreConfidence' : IDL.Opt(IDL.Nat),
    'status' : ApplicationStatus,
    'aiSuggestion' : IDL.Opt(IDL.Text),
    'source' : ApplicationSource,
    'jobType' : JobType,
    'fitScore' : IDL.Opt(IDL.Nat),
    'tags' : IDL.Vec(IDL.Text),
    'jobUrl' : IDL.Text,
    'appliedDate' : Timestamp,
    'notes' : IDL.Text,
    'companyName' : IDL.Text,
    'isHighPotential' : IDL.Bool,
    'salaryMax' : IDL.Opt(IDL.Nat),
    'salaryMin' : IDL.Opt(IDL.Nat),
    'position' : IDL.Text,
    'location' : IDL.Text,
  });
  const AppId = IDL.Nat;
  const UserId = IDL.Principal;
  const Application = IDL.Record({
    'id' : AppId,
    'fitScoreConfidence' : IDL.Opt(IDL.Nat),
    'status' : ApplicationStatus,
    'aiSuggestion' : IDL.Opt(IDL.Text),
    'source' : ApplicationSource,
    'jobType' : JobType,
    'userId' : UserId,
    'fitScore' : IDL.Opt(IDL.Nat),
    'tags' : IDL.Vec(IDL.Text),
    'lastUpdated' : Timestamp,
    'jobUrl' : IDL.Text,
    'appliedDate' : Timestamp,
    'notes' : IDL.Text,
    'companyName' : IDL.Text,
    'isHighPotential' : IDL.Bool,
    'salaryMax' : IDL.Opt(IDL.Nat),
    'salaryMin' : IDL.Opt(IDL.Nat),
    'position' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DateRange = IDL.Record({
    'toDate' : Timestamp,
    'fromDate' : Timestamp,
  });
  const ApplicationsOverTime = IDL.Record({
    'date' : Timestamp,
    'count' : IDL.Nat,
  });
  const ApplicationsByJobType = IDL.Record({
    'jobType' : JobType,
    'count' : IDL.Nat,
  });
  const ApplicationsBySource = IDL.Record({
    'source' : ApplicationSource,
    'count' : IDL.Nat,
  });
  const AnalyticsResult = IDL.Record({
    'offerRate' : IDL.Float64,
    'total' : IDL.Nat,
    'overTime' : IDL.Vec(ApplicationsOverTime),
    'interviewRate' : IDL.Float64,
    'avgTimeToOffer' : IDL.Float64,
    'responseRate' : IDL.Float64,
    'byJobType' : IDL.Vec(ApplicationsByJobType),
    'bySource' : IDL.Vec(ApplicationsBySource),
  });
  const GetApplicationsArgs = IDL.Record({
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'statusFilter' : IDL.Opt(ApplicationStatus),
  });
  const GetApplicationsResult = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'applications' : IDL.Vec(Application),
  });
  const AiInsight = IDL.Record({
    'message' : IDL.Text,
    'category' : IDL.Text,
    'priority' : IDL.Nat,
  });
  const ParsedJobDetails = IDL.Record({
    'fitScoreConfidence' : IDL.Opt(IDL.Nat),
    'rawJson' : IDL.Text,
    'jobType' : IDL.Opt(JobType),
    'fitScore' : IDL.Opt(IDL.Nat),
    'tags' : IDL.Vec(IDL.Text),
    'notes' : IDL.Text,
    'companyName' : IDL.Text,
    'salaryMax' : IDL.Opt(IDL.Nat),
    'salaryMin' : IDL.Opt(IDL.Nat),
    'position' : IDL.Text,
    'location' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateApplicationArgs = IDL.Record({
    'id' : AppId,
    'fitScoreConfidence' : IDL.Opt(IDL.Nat),
    'status' : ApplicationStatus,
    'aiSuggestion' : IDL.Opt(IDL.Text),
    'source' : ApplicationSource,
    'jobType' : JobType,
    'fitScore' : IDL.Opt(IDL.Nat),
    'tags' : IDL.Vec(IDL.Text),
    'jobUrl' : IDL.Text,
    'appliedDate' : Timestamp,
    'notes' : IDL.Text,
    'companyName' : IDL.Text,
    'isHighPotential' : IDL.Bool,
    'salaryMax' : IDL.Opt(IDL.Nat),
    'salaryMin' : IDL.Opt(IDL.Nat),
    'position' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addApplication' : IDL.Func([AddApplicationArgs], [Application], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteApplication' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAnalytics' : IDL.Func([DateRange], [AnalyticsResult], ['query']),
    'getApplication' : IDL.Func([IDL.Nat], [IDL.Opt(Application)], ['query']),
    'getApplications' : IDL.Func(
        [GetApplicationsArgs],
        [GetApplicationsResult],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGrokApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
    'getInsights' : IDL.Func([], [IDL.Vec(AiInsight)], []),
    'initSampleData' : IDL.Func([], [IDL.Nat], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'parseJobUrl' : IDL.Func([IDL.Text], [ParsedJobDetails], []),
    'searchApplications' : IDL.Func([IDL.Text], [IDL.Vec(Application)], []),
    'setGrokApiKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateApplication' : IDL.Func(
        [UpdateApplicationArgs],
        [IDL.Opt(Application)],
        [],
      ),
    'updateApplicationStatus' : IDL.Func(
        [IDL.Nat, ApplicationStatus],
        [IDL.Opt(Application)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };