/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddApplicationArgs {
  'fitScoreConfidence' : [] | [bigint],
  'status' : ApplicationStatus,
  'aiSuggestion' : [] | [string],
  'source' : ApplicationSource,
  'jobType' : JobType,
  'fitScore' : [] | [bigint],
  'tags' : Array<string>,
  'jobUrl' : string,
  'appliedDate' : Timestamp,
  'notes' : string,
  'companyName' : string,
  'isHighPotential' : boolean,
  'salaryMax' : [] | [bigint],
  'salaryMin' : [] | [bigint],
  'position' : string,
  'location' : string,
}
export interface AiInsight {
  'message' : string,
  'category' : string,
  'priority' : bigint,
}
export interface AnalyticsResult {
  'offerRate' : number,
  'total' : bigint,
  'overTime' : Array<ApplicationsOverTime>,
  'interviewRate' : number,
  'avgTimeToOffer' : number,
  'responseRate' : number,
  'byJobType' : Array<ApplicationsByJobType>,
  'bySource' : Array<ApplicationsBySource>,
}
export type AppId = bigint;
export interface Application {
  'id' : AppId,
  'fitScoreConfidence' : [] | [bigint],
  'status' : ApplicationStatus,
  'aiSuggestion' : [] | [string],
  'source' : ApplicationSource,
  'jobType' : JobType,
  'userId' : UserId,
  'fitScore' : [] | [bigint],
  'tags' : Array<string>,
  'lastUpdated' : Timestamp,
  'jobUrl' : string,
  'appliedDate' : Timestamp,
  'notes' : string,
  'companyName' : string,
  'isHighPotential' : boolean,
  'salaryMax' : [] | [bigint],
  'salaryMin' : [] | [bigint],
  'position' : string,
  'location' : string,
}
export type ApplicationSource = { 'referral' : null } |
  { 'network' : null } |
  { 'direct' : null } |
  { 'job_board' : null } |
  { 'recruiter' : null };
export type ApplicationStatus = { 'Applied' : null } |
  { 'Rejected' : null } |
  { 'Interviewing' : null } |
  { 'Offer' : null } |
  { 'Archived' : null };
export interface ApplicationsByJobType { 'jobType' : JobType, 'count' : bigint }
export interface ApplicationsBySource {
  'source' : ApplicationSource,
  'count' : bigint,
}
export interface ApplicationsOverTime { 'date' : Timestamp, 'count' : bigint }
export interface DateRange { 'toDate' : Timestamp, 'fromDate' : Timestamp }
export interface GetApplicationsArgs {
  'page' : bigint,
  'pageSize' : bigint,
  'statusFilter' : [] | [ApplicationStatus],
}
export interface GetApplicationsResult {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'applications' : Array<Application>,
}
export type JobType = { 'onsite' : null } |
  { 'remote' : null } |
  { 'hybrid' : null };
export interface ParsedJobDetails {
  'fitScoreConfidence' : [] | [bigint],
  'rawJson' : string,
  'jobType' : [] | [JobType],
  'fitScore' : [] | [bigint],
  'tags' : Array<string>,
  'notes' : string,
  'companyName' : string,
  'salaryMax' : [] | [bigint],
  'salaryMin' : [] | [bigint],
  'position' : string,
  'location' : string,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateApplicationArgs {
  'id' : AppId,
  'fitScoreConfidence' : [] | [bigint],
  'status' : ApplicationStatus,
  'aiSuggestion' : [] | [string],
  'source' : ApplicationSource,
  'jobType' : JobType,
  'fitScore' : [] | [bigint],
  'tags' : Array<string>,
  'jobUrl' : string,
  'appliedDate' : Timestamp,
  'notes' : string,
  'companyName' : string,
  'isHighPotential' : boolean,
  'salaryMax' : [] | [bigint],
  'salaryMin' : [] | [bigint],
  'position' : string,
  'location' : string,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addApplication' : ActorMethod<[AddApplicationArgs], Application>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteApplication' : ActorMethod<[bigint], boolean>,
  'getAnalytics' : ActorMethod<[DateRange], AnalyticsResult>,
  'getApplication' : ActorMethod<[bigint], [] | [Application]>,
  'getApplications' : ActorMethod<[GetApplicationsArgs], GetApplicationsResult>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInsights' : ActorMethod<[], Array<AiInsight>>,
  'initSampleData' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'parseJobUrl' : ActorMethod<[string], ParsedJobDetails>,
  'searchApplications' : ActorMethod<[string], Array<Application>>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateApplication' : ActorMethod<
    [UpdateApplicationArgs],
    [] | [Application]
  >,
  'updateApplicationStatus' : ActorMethod<
    [bigint, ApplicationStatus],
    [] | [Application]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];