/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type AppId = bigint;
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Application {
    id: AppId;
    fitScoreConfidence?: bigint;
    status: ApplicationStatus;
    aiSuggestion?: string;
    source: ApplicationSource;
    jobType: JobType;
    userId: UserId;
    fitScore?: bigint;
    tags: Array<string>;
    lastUpdated: Timestamp;
    jobUrl: string;
    appliedDate: Timestamp;
    notes: string;
    companyName: string;
    isHighPotential: boolean;
    salaryMax?: bigint;
    salaryMin?: bigint;
    position: string;
    location: string;
}
export interface UpdateApplicationArgs {
    id: AppId;
    fitScoreConfidence?: bigint;
    status: ApplicationStatus;
    aiSuggestion?: string;
    source: ApplicationSource;
    jobType: JobType;
    fitScore?: bigint;
    tags: Array<string>;
    jobUrl: string;
    appliedDate: Timestamp;
    notes: string;
    companyName: string;
    isHighPotential: boolean;
    salaryMax?: bigint;
    salaryMin?: bigint;
    position: string;
    location: string;
}
export interface GetApplicationsArgs {
    page: bigint;
    pageSize: bigint;
    statusFilter?: ApplicationStatus;
}
export interface AnalyticsResult {
    offerRate: number;
    total: bigint;
    overTime: Array<ApplicationsOverTime>;
    interviewRate: number;
    avgTimeToOffer: number;
    responseRate: number;
    byJobType: Array<ApplicationsByJobType>;
    bySource: Array<ApplicationsBySource>;
}
export interface ApplicationsBySource {
    source: ApplicationSource;
    count: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ParsedJobDetails {
    fitScoreConfidence?: bigint;
    rawJson: string;
    jobType?: JobType;
    fitScore?: bigint;
    tags: Array<string>;
    notes: string;
    companyName: string;
    salaryMax?: bigint;
    salaryMin?: bigint;
    position: string;
    location: string;
}
export type UserId = Principal;
export interface GetApplicationsResult {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    applications: Array<Application>;
}
export interface DateRange {
    toDate: Timestamp;
    fromDate: Timestamp;
}
export interface ApplicationsByJobType {
    jobType: JobType;
    count: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface AiInsight {
    message: string;
    category: string;
    priority: bigint;
}
export interface AddApplicationArgs {
    fitScoreConfidence?: bigint;
    status: ApplicationStatus;
    aiSuggestion?: string;
    source: ApplicationSource;
    jobType: JobType;
    fitScore?: bigint;
    tags: Array<string>;
    jobUrl: string;
    appliedDate: Timestamp;
    notes: string;
    companyName: string;
    isHighPotential: boolean;
    salaryMax?: bigint;
    salaryMin?: bigint;
    position: string;
    location: string;
}
export interface ApplicationsOverTime {
    date: Timestamp;
    count: bigint;
}
export enum ApplicationSource {
    referral = "referral",
    network = "network",
    direct = "direct",
    job_board = "job_board",
    recruiter = "recruiter"
}
export enum ApplicationStatus {
    Applied = "Applied",
    Rejected = "Rejected",
    Interviewing = "Interviewing",
    Offer = "Offer",
    Archived = "Archived"
}
export enum JobType {
    onsite = "onsite",
    remote = "remote",
    hybrid = "hybrid"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addApplication(args: AddApplicationArgs): Promise<Application>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteApplication(id: bigint): Promise<boolean>;
    getAnalytics(dateRange: DateRange): Promise<AnalyticsResult>;
    getApplication(id: bigint): Promise<Application | null>;
    getApplications(args: GetApplicationsArgs): Promise<GetApplicationsResult>;
    getCallerUserRole(): Promise<UserRole>;
    getGrokApiKey(): Promise<string | null>;
    getGrokModel(): Promise<string | null>;
    getInsights(): Promise<Array<AiInsight>>;
    initSampleData(): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    parseJobUrl(url: string): Promise<ParsedJobDetails>;
    searchApplications(searchQuery: string): Promise<Array<Application>>;
    setGrokApiKey(key: string): Promise<void>;
    setGrokModel(model: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateApplication(args: UpdateApplicationArgs): Promise<Application | null>;
    updateApplicationStatus(id: bigint, status: ApplicationStatus): Promise<Application | null>;
}
import type { AddApplicationArgs as _AddApplicationArgs, AnalyticsResult as _AnalyticsResult, AppId as _AppId, Application as _Application, ApplicationSource as _ApplicationSource, ApplicationStatus as _ApplicationStatus, ApplicationsByJobType as _ApplicationsByJobType, ApplicationsBySource as _ApplicationsBySource, ApplicationsOverTime as _ApplicationsOverTime, GetApplicationsArgs as _GetApplicationsArgs, GetApplicationsResult as _GetApplicationsResult, JobType as _JobType, ParsedJobDetails as _ParsedJobDetails, Timestamp as _Timestamp, UpdateApplicationArgs as _UpdateApplicationArgs, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addApplication(arg0: AddApplicationArgs): Promise<Application> {
        if (this.processError) {
            try {
                const result = await this.actor.addApplication(to_candid_AddApplicationArgs_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Application_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addApplication(to_candid_AddApplicationArgs_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Application_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteApplication(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteApplication(arg0);
            return result;
        }
    }
    async getAnalytics(arg0: DateRange): Promise<AnalyticsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics(arg0);
                return from_candid_AnalyticsResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics(arg0);
            return from_candid_AnalyticsResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplication(arg0: bigint): Promise<Application | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplication(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplication(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplications(arg0: GetApplicationsArgs): Promise<GetApplicationsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplications(to_candid_GetApplicationsArgs_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_GetApplicationsResult_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplications(to_candid_GetApplicationsArgs_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_GetApplicationsResult_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGrokApiKey(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGrokApiKey();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGrokApiKey();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGrokModel(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGrokModel();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGrokModel();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInsights(): Promise<Array<AiInsight>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInsights();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInsights();
            return result;
        }
    }
    async initSampleData(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.initSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSampleData();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async parseJobUrl(arg0: string): Promise<ParsedJobDetails> {
        if (this.processError) {
            try {
                const result = await this.actor.parseJobUrl(arg0);
                return from_candid_ParsedJobDetails_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.parseJobUrl(arg0);
            return from_candid_ParsedJobDetails_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchApplications(arg0: string): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchApplications(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchApplications(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async setGrokApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGrokApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGrokApiKey(arg0);
            return result;
        }
    }
    async setGrokModel(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGrokModel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGrokModel(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateApplication(arg0: UpdateApplicationArgs): Promise<Application | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplication(to_candid_UpdateApplicationArgs_n40(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplication(to_candid_UpdateApplicationArgs_n40(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateApplicationStatus(arg0: bigint, arg1: ApplicationStatus): Promise<Application | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AnalyticsResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalyticsResult): AnalyticsResult {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ApplicationSource_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationSource): ApplicationSource {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ApplicationStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Application_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Application): Application {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ApplicationsByJobType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationsByJobType): ApplicationsByJobType {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ApplicationsBySource_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationsBySource): ApplicationsBySource {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_GetApplicationsResult_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GetApplicationsResult): GetApplicationsResult {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_JobType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobType): JobType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ParsedJobDetails_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ParsedJobDetails): ParsedJobDetails {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Application]): Application | null {
    return value.length === 0 ? null : from_candid_Application_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobType]): JobType | null {
    return value.length === 0 ? null : from_candid_JobType_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AppId;
    fitScoreConfidence: [] | [bigint];
    status: _ApplicationStatus;
    aiSuggestion: [] | [string];
    source: _ApplicationSource;
    jobType: _JobType;
    userId: _UserId;
    fitScore: [] | [bigint];
    tags: Array<string>;
    lastUpdated: _Timestamp;
    jobUrl: string;
    appliedDate: _Timestamp;
    notes: string;
    companyName: string;
    isHighPotential: boolean;
    salaryMax: [] | [bigint];
    salaryMin: [] | [bigint];
    position: string;
    location: string;
}): {
    id: AppId;
    fitScoreConfidence?: bigint;
    status: ApplicationStatus;
    aiSuggestion?: string;
    source: ApplicationSource;
    jobType: JobType;
    userId: UserId;
    fitScore?: bigint;
    tags: Array<string>;
    lastUpdated: Timestamp;
    jobUrl: string;
    appliedDate: Timestamp;
    notes: string;
    companyName: string;
    isHighPotential: boolean;
    salaryMax?: bigint;
    salaryMin?: bigint;
    position: string;
    location: string;
} {
    return {
        id: value.id,
        fitScoreConfidence: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.fitScoreConfidence)),
        status: from_candid_ApplicationStatus_n12(_uploadFile, _downloadFile, value.status),
        aiSuggestion: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.aiSuggestion)),
        source: from_candid_ApplicationSource_n15(_uploadFile, _downloadFile, value.source),
        jobType: from_candid_JobType_n17(_uploadFile, _downloadFile, value.jobType),
        userId: value.userId,
        fitScore: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.fitScore)),
        tags: value.tags,
        lastUpdated: value.lastUpdated,
        jobUrl: value.jobUrl,
        appliedDate: value.appliedDate,
        notes: value.notes,
        companyName: value.companyName,
        isHighPotential: value.isHighPotential,
        salaryMax: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.salaryMax)),
        salaryMin: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.salaryMin)),
        position: value.position,
        location: value.location
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    offerRate: number;
    total: bigint;
    overTime: Array<_ApplicationsOverTime>;
    interviewRate: number;
    avgTimeToOffer: number;
    responseRate: number;
    byJobType: Array<_ApplicationsByJobType>;
    bySource: Array<_ApplicationsBySource>;
}): {
    offerRate: number;
    total: bigint;
    overTime: Array<ApplicationsOverTime>;
    interviewRate: number;
    avgTimeToOffer: number;
    responseRate: number;
    byJobType: Array<ApplicationsByJobType>;
    bySource: Array<ApplicationsBySource>;
} {
    return {
        offerRate: value.offerRate,
        total: value.total,
        overTime: value.overTime,
        interviewRate: value.interviewRate,
        avgTimeToOffer: value.avgTimeToOffer,
        responseRate: value.responseRate,
        byJobType: from_candid_vec_n23(_uploadFile, _downloadFile, value.byJobType),
        bySource: from_candid_vec_n26(_uploadFile, _downloadFile, value.bySource)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jobType: _JobType;
    count: bigint;
}): {
    jobType: JobType;
    count: bigint;
} {
    return {
        jobType: from_candid_JobType_n17(_uploadFile, _downloadFile, value.jobType),
        count: value.count
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    source: _ApplicationSource;
    count: bigint;
}): {
    source: ApplicationSource;
    count: bigint;
} {
    return {
        source: from_candid_ApplicationSource_n15(_uploadFile, _downloadFile, value.source),
        count: value.count
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    applications: Array<_Application>;
}): {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    applications: Array<Application>;
} {
    return {
        total: value.total,
        page: value.page,
        pageSize: value.pageSize,
        applications: from_candid_vec_n34(_uploadFile, _downloadFile, value.applications)
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fitScoreConfidence: [] | [bigint];
    rawJson: string;
    jobType: [] | [_JobType];
    fitScore: [] | [bigint];
    tags: Array<string>;
    notes: string;
    companyName: string;
    salaryMax: [] | [bigint];
    salaryMin: [] | [bigint];
    position: string;
    location: string;
}): {
    fitScoreConfidence?: bigint;
    rawJson: string;
    jobType?: JobType;
    fitScore?: bigint;
    tags: Array<string>;
    notes: string;
    companyName: string;
    salaryMax?: bigint;
    salaryMin?: bigint;
    position: string;
    location: string;
} {
    return {
        fitScoreConfidence: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.fitScoreConfidence)),
        rawJson: value.rawJson,
        jobType: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.jobType)),
        fitScore: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.fitScore)),
        tags: value.tags,
        notes: value.notes,
        companyName: value.companyName,
        salaryMax: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.salaryMax)),
        salaryMin: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.salaryMin)),
        position: value.position,
        location: value.location
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Applied: null;
} | {
    Rejected: null;
} | {
    Interviewing: null;
} | {
    Offer: null;
} | {
    Archived: null;
}): ApplicationStatus {
    return "Applied" in value ? ApplicationStatus.Applied : "Rejected" in value ? ApplicationStatus.Rejected : "Interviewing" in value ? ApplicationStatus.Interviewing : "Offer" in value ? ApplicationStatus.Offer : "Archived" in value ? ApplicationStatus.Archived : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referral: null;
} | {
    network: null;
} | {
    direct: null;
} | {
    job_board: null;
} | {
    recruiter: null;
}): ApplicationSource {
    return "referral" in value ? ApplicationSource.referral : "network" in value ? ApplicationSource.network : "direct" in value ? ApplicationSource.direct : "job_board" in value ? ApplicationSource.job_board : "recruiter" in value ? ApplicationSource.recruiter : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    onsite: null;
} | {
    remote: null;
} | {
    hybrid: null;
}): JobType {
    return "onsite" in value ? JobType.onsite : "remote" in value ? JobType.remote : "hybrid" in value ? JobType.hybrid : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApplicationsByJobType>): Array<ApplicationsByJobType> {
    return value.map((x)=>from_candid_ApplicationsByJobType_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApplicationsBySource>): Array<ApplicationsBySource> {
    return value.map((x)=>from_candid_ApplicationsBySource_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Application>): Array<Application> {
    return value.map((x)=>from_candid_Application_n9(_uploadFile, _downloadFile, x));
}
function to_candid_AddApplicationArgs_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddApplicationArgs): _AddApplicationArgs {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ApplicationSource_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationSource): _ApplicationSource {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ApplicationStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): _ApplicationStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_GetApplicationsArgs_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GetApplicationsArgs): _GetApplicationsArgs {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_JobType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): _JobType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateApplicationArgs_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateApplicationArgs): _UpdateApplicationArgs {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fitScoreConfidence?: bigint;
    status: ApplicationStatus;
    aiSuggestion?: string;
    source: ApplicationSource;
    jobType: JobType;
    fitScore?: bigint;
    tags: Array<string>;
    jobUrl: string;
    appliedDate: Timestamp;
    notes: string;
    companyName: string;
    isHighPotential: boolean;
    salaryMax?: bigint;
    salaryMin?: bigint;
    position: string;
    location: string;
}): {
    fitScoreConfidence: [] | [bigint];
    status: _ApplicationStatus;
    aiSuggestion: [] | [string];
    source: _ApplicationSource;
    jobType: _JobType;
    fitScore: [] | [bigint];
    tags: Array<string>;
    jobUrl: string;
    appliedDate: _Timestamp;
    notes: string;
    companyName: string;
    isHighPotential: boolean;
    salaryMax: [] | [bigint];
    salaryMin: [] | [bigint];
    position: string;
    location: string;
} {
    return {
        fitScoreConfidence: value.fitScoreConfidence ? candid_some(value.fitScoreConfidence) : candid_none(),
        status: to_candid_ApplicationStatus_n3(_uploadFile, _downloadFile, value.status),
        aiSuggestion: value.aiSuggestion ? candid_some(value.aiSuggestion) : candid_none(),
        source: to_candid_ApplicationSource_n5(_uploadFile, _downloadFile, value.source),
        jobType: to_candid_JobType_n7(_uploadFile, _downloadFile, value.jobType),
        fitScore: value.fitScore ? candid_some(value.fitScore) : candid_none(),
        tags: value.tags,
        jobUrl: value.jobUrl,
        appliedDate: value.appliedDate,
        notes: value.notes,
        companyName: value.companyName,
        isHighPotential: value.isHighPotential,
        salaryMax: value.salaryMax ? candid_some(value.salaryMax) : candid_none(),
        salaryMin: value.salaryMin ? candid_some(value.salaryMin) : candid_none(),
        position: value.position,
        location: value.location
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    page: bigint;
    pageSize: bigint;
    statusFilter?: ApplicationStatus;
}): {
    page: bigint;
    pageSize: bigint;
    statusFilter: [] | [_ApplicationStatus];
} {
    return {
        page: value.page,
        pageSize: value.pageSize,
        statusFilter: value.statusFilter ? candid_some(to_candid_ApplicationStatus_n3(_uploadFile, _downloadFile, value.statusFilter)) : candid_none()
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: AppId;
    fitScoreConfidence?: bigint;
    status: ApplicationStatus;
    aiSuggestion?: string;
    source: ApplicationSource;
    jobType: JobType;
    fitScore?: bigint;
    tags: Array<string>;
    jobUrl: string;
    appliedDate: Timestamp;
    notes: string;
    companyName: string;
    isHighPotential: boolean;
    salaryMax?: bigint;
    salaryMin?: bigint;
    position: string;
    location: string;
}): {
    id: _AppId;
    fitScoreConfidence: [] | [bigint];
    status: _ApplicationStatus;
    aiSuggestion: [] | [string];
    source: _ApplicationSource;
    jobType: _JobType;
    fitScore: [] | [bigint];
    tags: Array<string>;
    jobUrl: string;
    appliedDate: _Timestamp;
    notes: string;
    companyName: string;
    isHighPotential: boolean;
    salaryMax: [] | [bigint];
    salaryMin: [] | [bigint];
    position: string;
    location: string;
} {
    return {
        id: value.id,
        fitScoreConfidence: value.fitScoreConfidence ? candid_some(value.fitScoreConfidence) : candid_none(),
        status: to_candid_ApplicationStatus_n3(_uploadFile, _downloadFile, value.status),
        aiSuggestion: value.aiSuggestion ? candid_some(value.aiSuggestion) : candid_none(),
        source: to_candid_ApplicationSource_n5(_uploadFile, _downloadFile, value.source),
        jobType: to_candid_JobType_n7(_uploadFile, _downloadFile, value.jobType),
        fitScore: value.fitScore ? candid_some(value.fitScore) : candid_none(),
        tags: value.tags,
        jobUrl: value.jobUrl,
        appliedDate: value.appliedDate,
        notes: value.notes,
        companyName: value.companyName,
        isHighPotential: value.isHighPotential,
        salaryMax: value.salaryMax ? candid_some(value.salaryMax) : candid_none(),
        salaryMin: value.salaryMin ? candid_some(value.salaryMin) : candid_none(),
        position: value.position,
        location: value.location
    };
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): {
    Applied: null;
} | {
    Rejected: null;
} | {
    Interviewing: null;
} | {
    Offer: null;
} | {
    Archived: null;
} {
    return value == ApplicationStatus.Applied ? {
        Applied: null
    } : value == ApplicationStatus.Rejected ? {
        Rejected: null
    } : value == ApplicationStatus.Interviewing ? {
        Interviewing: null
    } : value == ApplicationStatus.Offer ? {
        Offer: null
    } : value == ApplicationStatus.Archived ? {
        Archived: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationSource): {
    referral: null;
} | {
    network: null;
} | {
    direct: null;
} | {
    job_board: null;
} | {
    recruiter: null;
} {
    return value == ApplicationSource.referral ? {
        referral: null
    } : value == ApplicationSource.network ? {
        network: null
    } : value == ApplicationSource.direct ? {
        direct: null
    } : value == ApplicationSource.job_board ? {
        job_board: null
    } : value == ApplicationSource.recruiter ? {
        recruiter: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): {
    onsite: null;
} | {
    remote: null;
} | {
    hybrid: null;
} {
    return value == JobType.onsite ? {
        onsite: null
    } : value == JobType.remote ? {
        remote: null
    } : value == JobType.hybrid ? {
        hybrid: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
